#Working with Numpy

In [1]:
import numpy as np

## Part 1: Create an 1D- array
* Create an array by arrange function
* Create an array by using linspace with retstep
* Create an array with random number in a range
* Create an array with zeros and ones
* Create an array with random and unique number

In [2]:
#Create an even number array has 10 elements in range [2,20]
even_numbers = np.arange(2,21,2)
even_numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [3]:
#Create a 1D array contains 5 elements which divide by 5 and leave a remainder of 1 (5x+1) in the range[1,21]
arr = np.arange(1,21,5)
arr

array([ 1,  6, 11, 16])

In [4]:
#Create a 1D array contains 11 elements in range (0,1). Retstep is step size between values
arr1 = np.linspace(0,1,11,dtype = int,retstep = True)

In [5]:
#Create a 1D array contains 5 elements is randommed from 1 to 20
np.random.seed(3)
arr2 = np.random.randint(1,20,5)
arr2

array([11,  4,  9,  1, 11])

In [6]:
#Create a 1D array contains 10 elements with odd index = 0 and remain is even number
arr3 = np.zeros(10,dtype=int)
arr3[1::2] = np.arange(1,10,2)
arr3

array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])

In [7]:
#Create a 1D array contains 10 elements and index [0,3,6,9] = 3 and remain is 1
arr4 = np.ones(10,dtype=int)
arr4[0::3] = 3
arr4

array([3, 1, 1, 3, 1, 1, 3, 1, 1, 3])

In [8]:
#Create a 1D array contains 5 elements which are unique and random dividing by 3 and smaller than 30
np.random.seed(5)
arr5 = np.arange(0,30,3)
print(f"The first array which divides by 3: {arr5}")
arr6 = np.random.choice(arr5,5,replace = False)
print(f"The second array which is choosen from arr5: {arr6}")

The first array which divides by 3: [ 0  3  6  9 12 15 18 21 24 27]
The second array which is choosen from arr5: [27 15  6 12 21]


## Part2: Create 2D-array
* Create 2D-array has unique elements and smaller than a number
* Create 2D-array with boundary values set to 1 and all other values set to 0
* Create 2d-array where the diagonal elements are set to 1 and all other elements are set to 0

In [9]:
#Create 2D-array size(3,4) has unique elements and smaller than 50
np.random.seed(1)
even = np.arange(0,50,2)
arr_2d = np.random.choice(even, (3,4),replace=False)
arr_2d

array([[28, 26, 34,  6],
       [42, 20, 36, 38],
       [ 8,  4, 40, 12]])

In [10]:
#Create 2D-array(6,6) with boundary values set to 1 and others = 0
arr7 = np.ones((6,6),dtype=int)
arr7[1:-1,1:-1]=0
arr7

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

In [11]:
#Create 2D-array where diagonal elements are set to 1 and all other elements are set to 0
arr8 = np.eye(3)
print(arr8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Part 3: Query
* Query with 1D
* Query with 2d

In [12]:
#From even_number arrays above, take element having index 3
even_numbers[3]

np.int64(8)

In [13]:
#Take elements from index 2 to index 4(inclue index 4)
even_numbers[2:5]

array([ 6,  8, 10])

In [14]:
#Take elements from even_numbers that is bigger than 10
even_numbers[even_numbers > 10]

array([12, 14, 16, 18, 20])

In [15]:
#Take elements from even_numbers both divides by 3 and bigger than 10
even_numbers[(even_numbers %3 == 0) & (even_numbers > 10)]

array([12, 18])

In [16]:
#From arr_2d abover, what is value in row 2 and col 3
arr_2d[2,3]

np.int64(12)

In [17]:
#show all values in row index 1
arr_2d[1]

array([42, 20, 36, 38])

In [18]:
#show all values in col index 2
arr_2d[:,2]

array([34, 36, 40])

In [19]:
#take all values bigger than 30 in arr_2d
arr_2d[arr_2d > 30]

array([34, 42, 36, 38, 40])

In [20]:
#take all values in col index 2 and divide by 4
arr_2d[arr_2d[:,2]%4 == 0]

array([[42, 20, 36, 38],
       [ 8,  4, 40, 12]])

In [21]:
#take all values in arr_2d which is in range (10,30)
arr_2d[(arr_2d >= 10) & (arr_2d < 31)]

array([28, 26, 20, 12])

## Part 4: Edit, add, delete values in array
* Edit in 1D
* Edit in 2D

In [22]:
#Add 22 to even_numbers array
even_numbers = np.concatenate([even_numbers,[22]])
even_numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [23]:
#Add 30 to index 5 of even_numbers
even_numbers = np.insert(even_numbers,5,30)
even_numbers

array([ 2,  4,  6,  8, 10, 30, 12, 14, 16, 18, 20, 22])

In [24]:
#Delete value has index = 7 and save to temp array
temp = np.delete(even_numbers,7)
temp

array([ 2,  4,  6,  8, 10, 30, 12, 16, 18, 20, 22])

In [25]:
#Delete value is 8 and save to temp
temp = np.delete(even_numbers,np.where(even_numbers == 8))
temp

array([ 2,  4,  6, 10, 30, 12, 14, 16, 18, 20, 22])

In [26]:
#Change all values < 10 to 10
even_numbers[even_numbers < 10] = 10
even_numbers

array([10, 10, 10, 10, 10, 30, 12, 14, 16, 18, 20, 22])

In [27]:
#2D
#Add new row [10,26,20,24] to arr_2d above
new = [[10,26,20,24]]
arr_2d = np.concatenate([arr_2d,new], axis=0)
arr_2d

array([[28, 26, 34,  6],
       [42, 20, 36, 38],
       [ 8,  4, 40, 12],
       [10, 26, 20, 24]])

In [28]:
#Add new col [50,60,70,80] to arr_2d
col = np.array([50,60,70,80]).reshape(4,1)
arr_2d = np.concatenate([arr_2d,col],axis=1)
arr_2d

array([[28, 26, 34,  6, 50],
       [42, 20, 36, 38, 60],
       [ 8,  4, 40, 12, 70],
       [10, 26, 20, 24, 80]])

In [29]:
#Create temp is a 2D array which is removed row index 2
temp = np.delete(arr_2d,2,axis=0)
temp

array([[28, 26, 34,  6, 50],
       [42, 20, 36, 38, 60],
       [10, 26, 20, 24, 80]])

In [30]:
#Create temp is a 2D array which is removed col index 3
temp = np.delete(arr_2d,3,axis=1)
temp

array([[28, 26, 34, 50],
       [42, 20, 36, 60],
       [ 8,  4, 40, 70],
       [10, 26, 20, 80]])

In [31]:
#Edit value in row 1 and col 2 = 30
arr_2d[1,2] = 30
arr_2d

array([[28, 26, 34,  6, 50],
       [42, 20, 30, 38, 60],
       [ 8,  4, 40, 12, 70],
       [10, 26, 20, 24, 80]])

In [32]:
#Edit values which are bigger than 10 and smaller than 20 in arr_2d = 20
arr_2d[(arr_2d > 10) & (arr_2d < 20)] = 20
arr_2d

array([[28, 26, 34,  6, 50],
       [42, 20, 30, 38, 60],
       [ 8,  4, 40, 20, 70],
       [10, 26, 20, 24, 80]])

In [33]:
#Edit values < 30 and %4 != 0 in row index 0 to 30
arr_2d[0, (arr_2d[0] < 30) & (arr_2d[0] %4 !=0)] = 30
arr_2d

array([[28, 30, 34, 30, 50],
       [42, 20, 30, 38, 60],
       [ 8,  4, 40, 20, 70],
       [10, 26, 20, 24, 80]])